export default {
    ENVIRONMENT: "DEV",
    POSTGRESQL_DB_HOST: process.env.POSTGRESQL_DB_HOST,
    POSTGRESQL_DB_USERNAME: process.env.POSTGRESQL_DB_USERNAME,
    POSTGRESQL_DB_PASSWORD: process.env.POSTGRESQL_DB_PASSWORD || "",
    JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
    JWT_EXPIRY_DURATION: 60 * 60 // 1 hour
}